import { CommerceContainer } from "./containers/worker";

/**
 * Cloudflare Environment Interface
 * 
 * This file is auto-generated by `wrangler types` command.
 * You can update it by running: pnpm cf-typegen
 */
interface CloudflareEnv {
  // Cloudflare Container binding
  COMMERCE_CONTAINER: DurableObjectNamespace<CommerceContainer>;
  
  // Static assets binding
  ASSETS: Fetcher;
}

declare global {
  namespace NodeJS {
    interface ProcessEnv extends CloudflareEnv {}
  }
}

export {};

